# Generated by Django 6.0.3 on 2026-03-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sessions_completed',
            new_name='sessions_learned',
        ),
        migrations.AddField(
            model_name='profile',
            name='sessions_taught',
            field=models.IntegerField(default=0),
        ),
    ]
